---
title: "Sentiment analysis"
author: "Marie Braüner Degnbol"
output: html_document
date: "2026-05-12"
---
```{r}
library(tidyverse)

#if(!require("devtools")) install.packages("devtools")

#devtools::install_github("Guscode/Sentida")1

library(Sentida)
library(readtext)

```

```{r}
#example of how the sentiment analysis works.
sentida("Det er ikke en dårlig dag")

```

```{r}
#We do a tibble, with name, year, party and context, first with crisis
kriser <- tibble(readtext("Kriser/*.txt",
                          docvarsfrom = "filenames",
                          docvarnames = c("navn","årstal","parti","kontekst"),
                          dvsep = "_"))


```

```{r}
kriser_sentiment<- kriser %>% 
  rowwise() %>% 
  mutate(sentida = sentida(text,output = "mean"))
```

```{r}
#We do a tibble, with name, year, party and context, non crisis

Ikke_kriser <- tibble(readtext("Ikke_kriser/*.txt",
                          docvarsfrom = "filenames",
                          docvarnames = c("navn","årstal","parti","kontekst"),
                          dvsep = "_"))

```

```{r}
Ikke_kriser_sentiment<- Ikke_kriser %>% 
  rowwise() %>% 
  mutate(sentida = sentida(text,output = "mean"))
```

```{r}
#Then we make a boxplot with both crisis and non-crisis 

library(ggplot2)

kriser_sentiment$gruppe <- "Kriser"
Ikke_kriser_sentiment$gruppe <- "Ikke-kriser"

alle_data <- bind_rows(kriser_sentiment,
                       Ikke_kriser_sentiment)

ggplot(alle_data, aes(x = gruppe, y = sentida)) +
  geom_boxplot()


```
```{r}
samlet_data <- bind_rows(kriser_sentiment,
                         Ikke_kriser_sentiment)

ggplot(samlet_data,
       aes(x = gruppe,
           y = sentida,
           fill = gruppe)) +
  geom_boxplot() +
  theme_minimal()

ggsave("sentiment_boks.jpeg",
       width = 10,
       height = 6)

```



```{r} 
#we change the colors 
samlet_data <- bind_rows(kriser_sentiment,
                         Ikke_kriser_sentiment)

ggplot(samlet_data,
       aes(x = gruppe,
           y = sentida,
           fill = gruppe)) +
  
  geom_boxplot() +
  
  scale_fill_manual(values = c("Kriser" = "red",
                               "Ikke-kriser" = "blue")) +
  
  theme_minimal() +
  
  labs(title = "Sentiment i kriser vs ikke-kriser",
       x = "Gruppe",
       y = "Sentiment score")

ggsave("sentiment_boks.jpeg",
       width = 10,
       height = 6)
```

```{r}
#then we make a point plot 
samlet_data <- samlet_data %>%
  mutate(label = paste(navn, årstal),
         årstal = as.numeric(årstal)) %>%
  arrange(årstal)

ggplot(samlet_data,
       aes(x = reorder(label, årstal),
           y = sentida,
           color = gruppe)) +
  geom_point(size = 3) +
  scale_color_manual(values = c("Kriser" = "red",
                                "Ikke-kriser" = "blue")) +
  labs(x = "Statsminister og årstal",
       y = "Sentiment værdi") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
                                   

#to save it
ggsave("sentiment_graf.jpeg",
       width = 10,
       height = 6)

```

